# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "The Judean People's Front"
tagline:          "I asked for a media empire, but the Elders of Zion only gave me a Twitter account and a blog."
description:      "I asked for a media empire, but the Elders of Zion only gave me a Twitter account and a blog."
url:              http://judeanpf.com
baseurl:          /

author:
  name:           'Brian Cohen'
  url:            http://judeanpf.com


# Custom vars
version:          2.1.1

github:
  repo:           https://github.com/JudeanPF/judeanpf.github.io
